import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { useState, useCallback, useRef, useEffect } from "react"
import styles from "../styles/Home.module.css"
import { Data } from "./api/chat"
import io, { Socket } from "socket.io-client"
import { DefaultEventsMap } from "@socket.io/component-emitter"
let socket: Socket<DefaultEventsMap, DefaultEventsMap>

const Home: NextPage = () => {
  const [playerMessage, setPlayerMessage] = useState("")
  const [loading, setLoading] = useState(false)
  const [npcResponse, setNpcResponse] = useState("")

  const playerNameRef = useRef<HTMLInputElement>(null)

  const setMessage = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    setPlayerMessage(() => e.target.value)
  }, [])

  // const sendMessage = useCallback(async () => {
  //   setLoading(true)
  //   const playerName = playerNameRef.current?.value

  //   const res = await fetch(
  //     `/api/chat?message=${playerMessage}&name=${playerName}`
  //   )

  //   const data = await res.json()

  //   console.log("DBG: data response", { data })

  //   const response: Data = JSON.parse(data)

  //   if (!response.success) {
  //     setLoading(false)
  //     console.log("Erro")
  //     return
  //   }

  //   setNpcResponse(response.text)
  //   setLoading(true)
  // }, [playerMessage, playerNameRef])

  useEffect(() => {
    async function startSocket() {
      socketInitializer()
    }

    startSocket()
  }, [])

  const socketInitializer = async () => {
    await fetch("/api/chat")
    socket = io()

    socket.on("server-message-received", (msg) => {
      setLoading(false)
      setNpcResponse(msg)
    })
  }

  const sendClientMessage = useCallback(async () => {
    setLoading(true)
    const playerName = playerNameRef.current?.value
    socket.emit("client-message-sent", {
      message: playerMessage,
      name: playerName,
    })
  }, [playerMessage, playerNameRef])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span>Your Name</span>
        <input ref={playerNameRef} disabled={loading}></input>
        <span>Message</span>
        <input value={playerMessage} onChange={setMessage} disabled={loading} />
        <button disabled={loading} onClick={() => sendClientMessage()}>
          Send Message
        </button>
        <h2>Response:</h2>
        <p>{npcResponse}</p>
      </main>
    </div>
  )
}

export default Home
